version: '3.3'

services:
  prestashop:
    image: prestashop/prestashop:${PS_VERSION:-latest}
    depends_on:
      - db
    ports:
      - "8081:80"
#    user: www-data
    env_file:
      - ./.env
    environment:
      DB_SERVER: db
      PS_DOMAIN: ${PS_DOMAIN:-localhost}
      PS_FOLDER_ADMIN: administration
    volumes:
      - ./:/var/www/html/modules/bg_prestasms
      #- ./prestashop:/var/www/html

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: prestashop
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - db:/var/lib/mysql

  adminer:
    image: adminer
    environment:
      ADMINER_DESIGN: "nette"
      ADMINER_DEFAULT_SERVER: "db"
    ports:
      - "8090:8080"

volumes:
  db: