services:
  prestashop:
    image: ghcr.io/bulkgate/prestasms:${PRESTASHOP_IMAGE_VERSION:-8.2.1-8.1}
    depends_on:
      - db
    ports:
      - ${PRESTASHOP_PORT:-80}:80
    environment:
      PS_DOMAIN: ${PRESTASHOP_DOMAIN:-localhost}
      PS_FOLDER_ADMIN: administration
      DB_SERVER: db
      DB_NAME: ${MYSQL_DATABASE:-prestashop}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/var/www/html/modules/bulkgate_sms_module_for_prestashop
      - /var/www/html/modules/bulkgate_sms_module_for_prestashop/vendor # volume mount override - not mounting vendor

  db:
    image: mariadb:10
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-prestashop}
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - db:/var/lib/mysql

  adminer:
    image: adminer
    environment:
      ADMINER_DESIGN: "nette"
      ADMINER_DEFAULT_SERVER: "db"
    ports:
      - ${ADMINER_PORT:-9000}:8080

volumes:
  db: