services:
  prestashop:
    image: ghcr.io/bulkgate/prestasms:8.2.0-7.4
    depends_on:
      - db
    ports:
      - "8081:80"
    env_file:
      - .env
    environment:
      DB_SERVER: db
      PS_DOMAIN: ${PS_DOMAIN:-localhost}
      PS_FOLDER_ADMIN: administration
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./prestashop:/var/www/html
      - .:/var/www/html/modules/bg_prestasms

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: prestashop
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - db:/var/lib/mysql

  adminer:
    image: adminer
    environment:
      ADMINER_DESIGN: "nette"
      ADMINER_DEFAULT_SERVER: "db"
    ports:
      - "8090:8080"

volumes:
  db: