version: '3.3'

services:
  prestashop:
    image: prestashop/prestashop:8.1.2-7.4-apache
    restart: always
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      DB_SERVER: db
      PS_INSTALL_DB: 1
      PS_INSTALL_AUTO: 1
      BULKGATE_DEBUG_HOST: https://portal.bulkgate.com
      BULKGATE_DEV_MODE: 0
    volumes:
      - ./:/var/www/html/modules/bg_prestasms

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: prestashop
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: "nette"
      ADMINER_DEFAULT_SERVER: "db"
    ports:
      - "8080:8080"

volumes:
  db: