# Defines all the parameters for services
parameters:
  bulkgate_module_name: "PrestaSMS" #_BG_PRESTASMS_NAME_
  bulkgate_module_author: "TOPefekt s.r.o." #_BG_PRESTASMS_AUTHOR_
  bulkgate_module_author_url: "https://www.bulkgate.com/" #_BG_PRESTASMS_AUTHOR_URL_
  bulkgate_module_min_ps_version: "1.7.5.0" #_BG_PRESTASMS_PS_MIN_VERSION_
  bulkgate_module_version: "5.0.10" #_BG_PRESTASMS_VERSION_
  bulkgate_module_url: "https://portal.bulkgate.com"
  bulkgate_module_settings_defaults:
    "main:dispatcher": 'asset'
    "main:synchronization": 'all'
    "main:language": 'auto'
    "main:language_mutation": false
    "main:delete_db": false
    "main:address_preference": 'delivery'
    "main:marketing_message_opt_in_enabled": false
    "main:marketing_message_opt_in_label": ''
    "main:marketing_message_opt_in_default": false
    "main:marketing_message_opt_in_url": ''

