services:

  # Symfony Controller - https://devdocs.prestashop-project.org/1.7/modules/concepts/controllers/admin-controllers/#how-to-declare-a-new-controller
  BulkGate\PrestaShop\Controller\AdminController:
    class: BulkGate\PrestaShop\Controller\AdminController
    autowire: false
    tags: [ controller.service_arguments ]
