# @see [_lagacy_link](https://devdocs.prestashop-project.org/1.7/modules/concepts/controllers/admin-controllers/tabs/)
bulkgate_main_app:
  path: prestasms
  methods: [GET]
  defaults:
    _controller: 'BulkGate\PrestaSms\Controller\AdminController::indexAction'
    _legacy_controller: AdminPrestaSmsConfigure
    _legacy_link: AdminPrestaSmsConfigure

bulkgate_proxy:
  path: prestasms/proxy-{action}
  methods: [POST]
  defaults:
    _controller: 'BulkGate\PrestaSms\Controller\AdminController::proxyAction'

bulkgate_debug:
  path: prestasms/debug
  methods: [GET]
  defaults:
    _controller: 'BulkGate\PrestaSms\Controller\AdminController::debugAction'
    _legacy_controller: AdminPrestaSmsDebug
    _legacy_link: AdminPrestaSmsDebug