main_app:
  path: prestasms/demo
  methods: [GET]
  defaults:
    _controller: 'BulkGate\Controller\AdminPrestaSmsController::demoAction'
    _legacy_link: AdminPrestaSms #https://devdocs.prestashop-project.org/1.7/modules/concepts/controllers/admin-controllers/tabs/