bulkgate_main_app:
  path: prestasms
  methods: [GET]
  defaults:
    _controller: 'BulkGate\Controller\AdminPrestaSmsController::indexAction'
    _legacy_link: AdminPrestaSms #https://devdocs.prestashop-project.org/1.7/modules/concepts/controllers/admin-controllers/tabs/

bulkgate_debug:
  path: prestasms/debug
  methods: [GET]
  defaults:
    _controller: 'BulkGate\Controller\AdminPrestaSmsController::debugAction'