# https://devdocs.prestashop-project.org/1.7/modules/concepts/controllers/admin-controllers/#how-to-declare-a-new-controller

parameters:
  bulkgate_module_name: "PrestaSMS" #_BG_PRESTASMS_NAME_
  bulkgate_module_author: "TOPefekt s.r.o." #_BG_PRESTASMS_AUTHOR_
  bulkgate_module_author_url: "https://www.bulkgate.com/" #_BG_PRESTASMS_AUTHOR_URL_
  bulkgate_module_min_ps_version: "1.7.5.0" #_BG_PRESTASMS_PS_MIN_VERSION_
  bulkgate_module_version: "5.0.10" #_BG_PRESTASMS_VERSION_

services:
  _defaults:
    autowire: true
    autoconfigure: true

  BulkGate\PrestaSms\:
    resource: "../src/"
    exclude: "../src/{_extension.php,init.php}"
