# https://devdocs.prestashop-project.org/1.7/modules/concepts/controllers/admin-controllers/#how-to-declare-a-new-controller

parameters:
  bulkgate_module_name: "PrestaSMS" #_BG_PRESTASMS_NAME_
  bulkgate_module_author: "TOPefekt s.r.o." #_BG_PRESTASMS_AUTHOR_
  bulkgate_module_author_url: "https://www.bulkgate.com/" #_BG_PRESTASMS_AUTHOR_URL_
  bulkgate_module_min_ps_version: "1.7.5.0" #_BG_PRESTASMS_PS_MIN_VERSION_
  bulkgate_module_version: "5.0.10" #_BG_PRESTASMS_VERSION_

services:
  _defaults:
    autowire: true
    autoconfigure: true

  #alias PrestaShop classes - we need this
  PrestaShop\PrestaShop\Adapter\OrderState\OrderStateDataProvider: #'@prestashop.adapter.data_provider.order_state'
  PrestaShop\PrestaShop\Adapter\OrderReturnState\OrderReturnStateDataProvider: #'@prestashop.adapter.data_provider.order_return_state'
  PrestaShop\PrestaShop\Adapter\Language\LanguageDataProvider: #'@prestashop.adapter.data_provider.language'
  PrestaShop\PrestaShop\Adapter\Shop\Context: #'@prestashop.adapter.shop.context'
  PrestaShop\PrestaShop\Adapter\Shop\Url\BaseUrlProvider: #'@prestashop.adapter.shop.url.base_url_provider'
    arguments:
      - "@=service('prestashop.adapter.legacy.context').getContext().link"
  PrestaShop\PrestaShop\Adapter\Employee\ContextEmployeeProvider: #'@prestashop.adapter.data_provider.employee'
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext().employee'

  BulkGate\PrestaSms\:
    resource: "../src/"

  BulkGate\Plugin\:
    resource: "../vendor/bulkgate/plugin/src"
    exclude:
      - "../vendor/bulkgate/plugin/src/**/exceptions.php"
      - "../vendor/bulkgate/plugin/src/compatibility.php"


  BulkGate\PrestaSms\Eshop\Configuration:
    arguments:
      $version_number: '%bulkgate_module_version%'

  BulkGate\Plugin\Event\Loader:
    arguments:
      $loaders:
        - '@BulkGate\PrestaSms\Event\Loader\Shop'
        - '@BulkGate\PrestaSms\Event\Loader\Product'
        - '@BulkGate\PrestaSms\Event\Loader\Post'
        - '@BulkGate\PrestaSms\Event\Loader\OrderStatus'
        - '@BulkGate\PrestaSms\Event\Loader\Order'
        - '@BulkGate\PrestaSms\Event\Loader\Extension'
        - '@BulkGate\PrestaSms\Event\Loader\Customer'

  BulkGate\Plugin\Localization\FormatterIntl:
    arguments:
      $language: '@=service("BulkGate\\Plugin\\Localization\\LanguageSettings").get()' #todo: je to opravdu hodnota kterou hledame?

  BulkGate\Plugin\Localization\Formatter: '@BulkGate\Plugin\Localization\FormatterIntl' #todo: conditional formatter service. Mozna pouzit localization primo z prestashopu?

  BulkGate\Plugin\IO\ConnectionFactory:
    arguments:
      $application_url: '@=service("BulkGate\\PrestaSms\\Eshop\\Configuration").url()'
      $application_product: '@=service("BulkGate\\PrestaSms\\Eshop\\Configuration").product()'

  BulkGate\Plugin\IO\Connection:
    factory: ['@BulkGate\Plugin\IO\ConnectionFactory', 'create']

  BulkGate\Plugin\Localization\LanguageSettings:
    arguments:
      $iso: '@=service("prestashop.adapter.legacy.context").getEmployeeLanguageIso()' #todo: zjistit jak dostat tuto informaci mimo legacy kontext

  BulkGate\Plugin\IO\Url:
    arguments:
      $url: 'https://portal.bulkgate.com'

  BulkGate\Plugin\Event\Hook:
    arguments:
      $version: "1.0"

  # Alias interfaces - use local implementations
  BulkGate\Plugin\Eshop\Configuration: '@BulkGate\PrestaSms\Eshop\Configuration'
  BulkGate\Plugin\Settings\Repository\Settings: '@BulkGate\PrestaSms\Settings\Repository\SettingsDatabase'
  BulkGate\Plugin\Settings\Repository\Synchronization: '@BulkGate\PrestaSms\Settings\Repository\SynchronizationDatabase'
  BulkGate\Plugin\Event\Repository\Asynchronous: '@BulkGate\PrestaSms\Event\Repository\AsynchronousDatabase'