# https://devdocs.prestashop-project.org/1.7/modules/concepts/controllers/admin-controllers/#how-to-declare-a-new-controller

imports:
  - { resource: ./includes/parameters.yml}
  - { resource: ./includes/parameters.local.yml, ignore_errors: not_found}

services:
  _defaults:
    autowire: true
    autoconfigure: true

  #Adapter classes services

  PrestaShop\PrestaShop\Adapter\OrderState\OrderStateDataProvider: #'@prestashop.adapter.data_provider.order_state'
  PrestaShop\PrestaShop\Adapter\OrderReturnState\OrderReturnStateDataProvider: #'@prestashop.adapter.data_provider.order_return_state'
  PrestaShop\PrestaShop\Adapter\Language\LanguageDataProvider: #'@prestashop.adapter.data_provider.language'
  PrestaShop\PrestaShop\Adapter\Shop\Context: #'@prestashop.adapter.shop.context'
  PrestaShop\PrestaShop\Adapter\Shop\Url\BaseUrlProvider: #'@prestashop.adapter.shop.url.base_url_provider'
    arguments:
      - "@=service('prestashop.adapter.legacy.context').getContext().link"
  PrestaShop\PrestaShop\Adapter\Employee\ContextEmployeeProvider: #'@prestashop.adapter.data_provider.employee'
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext().employee'

  # Module

  BulkGate\PrestaSms\:
    resource: "../src/"

  BulkGate\Plugin\:
    resource: "../vendor/bulkgate/plugin/src"
    exclude:
      - "../vendor/bulkgate/plugin/src/**/exceptions.php"
      - "../vendor/bulkgate/plugin/src/compatibility.php"


  BulkGate\PrestaSms\Eshop\Configuration:
    arguments:
      $version_number: '%bulkgate_module_version%'

  BulkGate\Plugin\Event\Loader:
    arguments:
      $loaders:
        - '@BulkGate\PrestaSms\Event\Loader\Order'
        - '@BulkGate\PrestaSms\Event\Loader\OrderStatus'
        - '@BulkGate\PrestaSms\Event\Loader\Customer'
        - '@BulkGate\PrestaSms\Event\Loader\Shop'
        - '@BulkGate\PrestaSms\Event\Loader\Product'
        - '@BulkGate\PrestaSms\Event\Loader\Post'
        - '@BulkGate\PrestaSms\Event\Loader\Extension'

  BulkGate\Plugin\Localization\Formatter:
    factory: ['BulkGate\PrestaSms\Localization\FormatterFactory', 'create']
    arguments:
      $language: '@=service("BulkGate\\Plugin\\Localization\\LanguageSettings").get()'

  BulkGate\Plugin\Settings\Settings:
    calls:
      - method: setDefaultSettings
        arguments:
          - '%bulkgate_module_settings_defaults%'

  BulkGate\Plugin\IO\ConnectionFactory:
    arguments:
      $application_url: '@=service("BulkGate\\PrestaSms\\Eshop\\Configuration").url()'
      $application_product: '@=service("BulkGate\\PrestaSms\\Eshop\\Configuration").product()'

  BulkGate\Plugin\IO\Connection:
    factory: ['@BulkGate\Plugin\IO\ConnectionFactory', 'create']

  BulkGate\Plugin\Localization\LanguageSettings:
    arguments:
      $iso: '@=service("prestashop.adapter.legacy.context").getEmployeeLanguageIso()' #todo: zjistit jak dostat tuto informaci mimo legacy kontext

  BulkGate\Plugin\IO\Url:
    arguments:
      $url: '%bulkgate_module_url%'

  BulkGate\Plugin\Event\Hook:
    arguments:
      $version: "1.0"

  # Alias interfaces - use local implementations
  BulkGate\Plugin\Eshop\Configuration: '@BulkGate\PrestaSms\Eshop\Configuration'