name: Build docker images

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - '.docker/**'
      - '.github/workflows/docker.yml'

jobs:
  init-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read version matrix
        id: set-matrix
        run: echo "matrix=$(jq -c . < .docker/versions.json)" >> $GITHUB_OUTPUT

  build:
    needs: init-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJSON(needs.init-matrix.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare executable
        run: chmod +x .docker/generate.sh

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: .docker/generate.sh --no-emit-version --php-version ${{ matrix.php }} --prestashop-version ${{ matrix.prestashop }}