name: Run application tests

on:
  push:
    paths-ignore:
      - .docker/**
      - .github/**
      - '!.github/workflows/tests.yml'

jobs:
  tests:
    runs-on: ubuntu-latest

    # minimum and maximum supported version
    strategy:
      matrix:
        include:
          - php: 7.4
            prestashop: 1.7.8.0
          - php: 7.4
            prestashop: 8.2.1
          - php: 8.1
            prestashop: 8.2.1

    container: ghcr.io/bulkgate/prestasms:${{ matrix.prestashop }}-${{ matrix.php }}

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run test suite
        run: composer run tester

      - name: Run static analysis
        run: composer run phpstan

  coverage:
    runs-on: ubuntu-latest

    container: ghcr.io/bulkgate/prestasms:8.2.1-8.1

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run coverage
        run: composer run coverage

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.html